/**
 * The design system's public surface.
 *
 * Import from `@/design-system` rather than reaching into `ui/*` — it keeps
 * call sites stable if a component is later split or renamed.
 */
export { cn } from './cn'
export { ThemeProvider, useTheme, type ThemeMode } from './theme-provider'

export * from './ui/accordion'
export * from './ui/alert'
export * from './ui/alert-dialog'
export * from './ui/app-shell'
export * from './ui/avatar'
export * from './ui/badge'
export * from './ui/button'
export * from './ui/card'
export * from './ui/checkbox'
export * from './ui/collapsible'
export * from './ui/combobox'
export * from './ui/dialog'
export * from './ui/drawer'
export * from './ui/empty-state'
export * from './ui/field'
export * from './ui/input'
export * from './ui/menu'
export * from './ui/number-field'
export * from './ui/popover'
export * from './ui/progress'
export * from './ui/radio-group'
export * from './ui/scroll-area'
export * from './ui/select'
export * from './ui/separator'
export * from './ui/skeleton'
export * from './ui/slider'
export * from './ui/stack'
export * from './ui/switch'
export * from './ui/table'
export * from './ui/tabs'
export * from './ui/text'
export * from './ui/textarea'
export * from './ui/theme-toggle'
export * from './ui/toast'
export * from './ui/toggle-group'
export * from './ui/tooltip'
