#!/usr/bin/env node
/**
 * Generates .claude/skills/fragments-ui/components.md from the component
 * contracts that @usefragments/ui ships inside node_modules.
 *
 * Why this exists: an agent that guesses component props writes code that does
 * not compile (or worse, compiles and silently does nothing — see the
 * value-first `onChange` note in src/routes/form-demo.tsx). The package already
 * carries machine-readable contracts describing every prop, its type, default
 * and allowed values. This turns them into one file the agent can read.
 *
 * Run after upgrading @usefragments/ui:  pnpm gen:catalog
 */
import { createRequire } from 'node:module'
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'

const require = createRequire(import.meta.url)

const PKG = '@usefragments/ui'
const OUT = '.claude/skills/fragments-ui/components.md'

function packageRoot() {
  // Resolve via package.json so this works with pnpm's symlinked store.
  return dirname(require.resolve(`${PKG}/package.json`))
}

function readContracts(root) {
  const componentsDir = join(root, 'src', 'components')
  const entries = readdirSync(componentsDir, { withFileTypes: true })
  const out = []

  for (const entry of entries) {
    if (!entry.isDirectory()) continue
    const file = join(componentsDir, entry.name, `${entry.name}.contract.json`)
    try {
      out.push({ dir: entry.name, ...JSON.parse(readFileSync(file, 'utf8')) })
    } catch {
      // Not every component ships a contract (Button, for one). Fall back to
      // listing it so the agent still knows it exists and where to look.
      out.push({ dir: entry.name, name: entry.name, noContract: true })
    }
  }

  return out.sort((a, b) => a.name.localeCompare(b.name))
}

function render(contracts, version) {
  const withContract = contracts.filter((c) => !c.noContract)
  const byCategory = new Map()

  for (const c of contracts) {
    const key = c.category ?? 'other'
    if (!byCategory.has(key)) byCategory.set(key, [])
    byCategory.get(key).push(c)
  }

  const lines = [
    '<!-- GENERATED by scripts/gen-catalog.mjs — do not edit by hand. -->',
    `<!-- Source: ${PKG}@${version} -->`,
    '',
    `# Fragments component catalogue (${PKG}@${version})`,
    '',
    `${contracts.length} components. ${withContract.length} ship a machine-readable contract.`,
    '',
    'Import everything from the package root unless the component is listed',
    'under "Subpath imports" at the bottom:',
    '',
    '```tsx',
    "import { Button, Card, Stack } from '@usefragments/ui'",
    '```',
    '',
    '## Index by category',
    '',
  ]

  for (const [category, items] of [...byCategory].sort()) {
    lines.push(
      `**${category}** — ${items
        .map((i) => i.name)
        .sort()
        .join(', ')}`,
      '',
    )
  }

  lines.push('---', '', '## Components', '')

  for (const c of contracts) {
    lines.push(`### ${c.name}`)
    lines.push('')
    if (c.description) lines.push(c.description, '')

    const meta = []
    if (c.category) meta.push(`category: ${c.category}`)
    if (c.status) meta.push(`status: ${c.status}`)
    if (c.tags?.length) meta.push(`tags: ${c.tags.join(', ')}`)
    if (meta.length) lines.push(`_${meta.join(' · ')}_`, '')

    if (c.noContract) {
      lines.push(
        `No contract shipped. Read the typings for exact props:`,
        `\`node_modules/${PKG}/dist/components/${c.dir}/index.d.ts\``,
        '',
      )
      continue
    }

    if (c.propsSummary?.length) {
      lines.push('```')
      for (const p of c.propsSummary) lines.push(p)
      lines.push('```', '')
    }

    lines.push(
      `Full contract: \`node_modules/${PKG}/src/components/${c.dir}/${c.dir}.contract.json\``,
      '',
    )
  }

  lines.push(
    '---',
    '',
    '## Subpath imports',
    '',
    'These components live behind subpath exports and need an optional peer',
    'dependency installed before use. Install the peer when you first import one.',
    '',
    '| Import | Peer dependency required |',
    '| --- | --- |',
    '| `@usefragments/ui/chart` | `recharts` |',
    '| `@usefragments/ui/data-table`, `/table` | `@tanstack/react-table`, `@tanstack/react-virtual` |',
    '| `@usefragments/ui/editor` | `@tiptap/react`, `@tiptap/starter-kit`, `@tiptap/extension-link` |',
    '| `@usefragments/ui/datepicker` | `react-day-picker`, `date-fns` |',
    '| `@usefragments/ui/colorpicker` | `react-colorful` |',
    '| `@usefragments/ui/markdown` | `react-markdown`, `remark-gfm` |',
    '| `@usefragments/ui/codeblock` | `shiki` |',
    '',
    'They are declared as **optional** peers, so leaving them uninstalled is',
    'supported and produces no warnings.',
    '',
  )

  return lines.join('\n')
}

const root = packageRoot()
const version = JSON.parse(
  readFileSync(join(root, 'package.json'), 'utf8'),
).version
const contracts = readContracts(root)

mkdirSync(dirname(OUT), { recursive: true })
writeFileSync(OUT, render(contracts, version))

console.log(
  `Wrote ${OUT} — ${contracts.length} components from ${PKG}@${version}`,
)
